// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'help-files/index', // path relative to /docs (no .md)
      label: 'Official Game Guide',         // This is how it appears in the sidebar
    },
    {
      type: 'doc',
      id: 'help-files/introduction', // path relative to /docs (no .md)
      label: 'Introduction',         // This is how it appears in the sidebar
    },
    {
      type: 'category',
      label: 'Games',
      items: [
        {
          type: 'autogenerated',
          dirName: 'help-files/games', // folder under /docs
        },
      ],
    },
    {
      type: 'category',
      label: 'Board Configurations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'help-files/board-configurations',
        },
      ],
    },
  ],

};

export default sidebars;
